AWSTemplateFormatVersion: '2010-09-09'
Description: "Desafio DIO - Criação de instância EC2 com Apache e Firewall (Security Group)"

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Permitir acesso SSH e HTTP"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07860a2d7eb515d9a  
      InstanceType: t3.micro          
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      KeyName: Name 
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Meu Servidor Web EC2 com Apache no CloudFormation!</h1>" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: ServidorWeb